export const FETCH_REPO_BY_NAME_REQUEST = 'FETCH_REPO_BY_NAME_REQUEST';
export const FETCH_REPO_BY_NAME_SUCCESS = 'FETCH_REPO_BY_NAME_SUCCESS'; 
export const FETCH_REPO_BY_NAME_ERROR = 'FETCH_REPO_BY_NAME_ERROR';  

export const FETCH_README_REQUEST = 'FETCH_README_REQUEST';
export const FETCH_README_SUCCESS = 'FETCH_README_SUCCESS'; 
export const FETCH_README_ERROR = 'FETCH_README_ERROR'; 

export const FETCH_REPO_REQUEST = 'FETCH_REPO_REQUEST';
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'; 
export const FETCH_REPO_ERROR = 'FETCH_REPO_ERROR'; 

export const FETCH_README_HTML_REQUEST = 'FETCH_README_HTML_REQUEST';
export const FETCH_README_HTML_SUCCESS = 'FETCH_README_HTML_SUCCESS'; 
export const FETCH_README_HTML_ERROR = 'FETCH_README_HTML_ERROR'; 