export const FETCH_REPO_BY_NAME_REQUEST = 'FETCH_REPO_BY_NAME_REQUEST';
export const FETCH_REPO_BY_NAME_SUCCESS = 'FETCH_REPO_BY_NAME_SUCCESS'; 
export const FETCH_REPO_BY_NAME_ERROR = 'FETCH_REPO_BY_NAME_ERROR';  